ALTER TABLE properties RENAME COLUMN weight TO atomic_mass;
ALTER TABLE properties RENAME COLUMN melting_point TO melting_point_celsius;
ALTER TABLE properties RENAME COLUMN boiling_point TO boiling_point_celsius;
ALTER TABLE properties ALTER COLUMN boiling_point_celsius SET NOT NULL;
ALTER TABLE properties ALTER COLUMN melting_point_celsius SET NOT NULL;
ALTER TABLE elements ADD UNIQUE(symbol);
ALTER TABLE elements ADD UNIQUE(name);
ALTER TABLE elements ALTER COLUMN symbol SET NOT NULL;
ALTER TABLE elements ALTER COLUMN name SET NOT NULL;
ALTER TABLE properties ADD FOREIGN KEY(atomic_number) REFERENCES elements(atomic_number);
CREATE TABLE types();
ALTER TABLE types ADD COLUMN type_id INT PRIMARY KEY;
ALTER TABLE types ADD COLUMN type VARCHAR NOT NULL;
INSERT INTO types(type_id, type) VALUES (1, 'metal');
INSERT INTO types(type_id, type) VALUES (2, 'metalloid');
INSERT INTO types(type_id, type) VALUES (3, 'nonmetal');
ALTER TABLE properties ADD COLUMN type_id INT NOT NULL DEFAULT 0;
UPDATE properties SET type_id=1 WHERE type='metal';
UPDATE properties SET type_id=2 WHERE type='metalloid';
UPDATE properties SET type_id=3 WHERE type='nonmetal';
ALTER TABLE properties ADD FOREIGN KEY(type_id) REFERENCES types(type_id);
UPDATE elements SET symbol=INITCAP(symbol);
ALTER TABLE properties ALTER COLUMN atomic_mass SET DATA TYPE DECIMAL USING atomic_mass::REAL;
INSERT INTO elements(atomic_number, name, symbol) VALUES (9, 'Fluorine', 'F');
INSERT INTO properties(atomic_number, atomic_mass, type, type_id, melting_point_celsius, boiling_point_celsius) VALUES (9, 18.998, 'nonmetal', 3, -220, -188.1);
INSERT INTO elements(atomic_number, name, symbol) VALUES (10, 'Neon,, 'Ne');
INSERT INTO properties(atomic_number, atomic_mass, type, type_id, melting_point_celsius, boiling_point_celsius) VALUES (10, 20.18, 'nonmetal', 3, -248.6, -246.1);
DELETE FROM properties WHERE atomic_number=1000;
DELETE FROM elements  WHERE atomic_number=1000;
ALTER TABLE properties DROP COLUMN type;
